# Generated by Django 4.0.6 on 2022-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_myuser_email_alter_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
