# Generated by Django 4.0.6 on 2022-08-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0007_remove_cliente_id_usuario'),
        ('Login', '0006_alter_myuser_id_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id_cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
    ]
