# Generated by Django 4.0.6 on 2022-08-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
        ('Login', '0007_alter_myuser_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id_empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado'),
        ),
    ]
