# Generated by Django 4.0.6 on 2022-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('DNI', models.IntegerField(unique=True, verbose_name='DNI')),
                ('fecha_de_nac', models.DateField()),
                ('tipo_cliente', models.CharField(choices=[('C', 'Classic'), ('G', 'Gold'), ('B', 'Black')], max_length=1)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
    ]
