# Generated by Django 4.0.6 on 2022-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0005_alter_cliente_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='DNI',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
