# Generated by Django 4.0.6 on 2022-08-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0006_alter_cliente_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_usuario',
        ),
    ]
