# Generated by Django 4.0.6 on 2022-08-31 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursales', '0001_initial'),
        ('Clientes', '0007_remove_cliente_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Sucursales.sucursal'),
            preserve_default=False,
        ),
    ]
