# Generated by Django 4.0.6 on 2022-09-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0008_cliente_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
