# Generated by Django 4.0.6 on 2022-08-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sucursal', models.IntegerField()),
                ('nombre_sucursal', models.TextField()),
                ('direccion_sucursal', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Sucursales',
            },
        ),
    ]
